name: Deploy to Aliyun OSS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Aliyun OSS
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: "${{ secrets.ALIYUN_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"

    - name: Upload to OSS
      run: |
        ossutil cp -rf dist/ oss://avatar-maker-2024/
        ossutil set-meta oss://avatar-maker-2024/index.html Cache-Control:no-cache --update -f